[window]

opacity = 0.9

[font]

normal = { family = "HackNerdFont", style = "Regular"}

size = 11

[colors.primary]
background = "0x000000"

[cursor]

style = { shape = "Beam", blinking = "On" }

[selection]

save_to_clipboard = true

#[colors]

#transparent_background_colors = true
